project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "case-studies/*.qmd"
    - "contents/*.qmd"
    - "!slides/"
    
website:
  page-navigation: true
  title: "TCGA Data Analysis with R"
  description: "Homepage for workshop on TACGA Data Analysis with R"
  site-url: "TCGADataAnalysiswithR"
  favicon: "images/logo.png"    
  repo-url: https://github.com/omicscenter/TCGADataAnalysiswithR
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@hossainlab"
    image: "/images/logo.png"
  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2023, Md. Jubayer Hossain"
    background: "#758283"

  sidebar:
      background: "#758283"
      logo: "images/logo.png"
      pinned: true
      align: center
      tools:
        - icon: globe
          href: https://omicscenter.github.io/
        - icon: github
          href: https://github.com/omicscenter
        - icon: facebook
          href: https://www.facebook.com/omicscenter
        - icon: linkedin
          href: https://www.linkedin.com/company/chiral-bangladesh/
 
      style: docked
      contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: prework.qmd
        text: Prework
      - href: setup-guide.qmd
        text: Setup Guide
      - href: resources.qmd
        text: Resources
      - href: q-and-a.qmd
        text: FAQs
format:
  html:
    theme: [journal, theme.scss]
    toc: true
    code-line-numbers: true
    code-link: true 
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y

editor: source



